version: '3.0'

services:
  nginx:
    container_name: NGINX
    image: nginx:stable
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../src:/app
      - ./logs/nginx:/var/log/nginx
    ports:
      - 80:80
    depends_on:
      - php
      - mysql
    networks:
      - php-network

  php:
    container_name: PHP
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.php
    volumes:
      - ../src:/app
      - ../docker/logs/xdebug:/var/log/xdebug
    networks:
      - php-network

  mysql:
    container_name: MYSQL
    image: mysql:8.0.31
    volumes:
      - ./logs/mysql:/var/log/mysql
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
    networks:
      - php-network

networks:
  php-network:
    driver: bridge
